[Fix]task_spec.rbの修正
ryota1116/rspec_app_exam pull request #1
Opened 2020-05-09 02:45 UTC by ryota1116

[概要]
## 修正内容
- インスタンス変数の代わりに、let文を使用。
- `spec/factories/tasks.rb`でtrait文を用い、タスクが完了済みのテストデータを作成。
- `タスクが削除されること`のテストが成功するように修正。

## 未修正のテスト
- 'Project詳細からTask一覧ページにアクセスした場合、Taskが表示されること'、
- 'Taskを編集した場合、一覧画面で編集後の内容が表示されること'

2020-05-09 02:48 UTC, ryota1116 commented on spec/system/task_spec.rb
> +        expect(page).not_to have_selector 'td', text: task.title
`expect(page).not_to have_content task.title`というマッチャだと、`app/views/tasks/index.html.erb`の`<th>Title</th>`という文字列に引っ掛かり、テストが失敗していたようです。

2020-05-09 03:06 UTC, ryota1116 commented
#### テスト実行時の実行時のキャプチャ
<img width="927" alt="スクリーンショット 2020-05-09 12 05 58" src="https://user-images.githubusercontent.com/60560627/81462433-738b3100-91ed-11ea-999e-dc6e633899fc.png">

2020-05-09 03:42 UTC, ryota1116 commented on spec/system/task_spec.rb
> +        switch_to_window(windows.last)
`app/views/projects/show.html.erb`の
`<%= link_to 'View Todos', project_tasks_path(@project), target:'_blank', rel: 'noopener' %>`をクリックすると、ページ遷移せずに新しいタブが開くようになっていたので、テストコードでも別タブに移動するよう修正したらテストが通りました。

2020-05-09 03:58 UTC, yuji91 commented on spec/system/task_spec.rb
> +        switch_to_window(windows.last)
byebugで止めてpage.bodyで確認するとhtmlの内容が確認できるのでそこから判断することも可能ですね。`

2020-05-09 04:00 UTC, yuji91 requested changes

2020-05-09 04:00 UTC, yuji91 commented on spec/system/task_spec.rb
> +  let(:project) { FactoryBot.create(:project) }
`FactoryBot.`という記載は設定に追記して省略してしまいましょう。

2020-05-09 04:00 UTC, yuji91 commented on spec/system/task_spec.rb
> +        expect(find('.task_list')).to have_content task.deadline.strftime('%-m/%d %-H:%M')
VIew側で使っているメソッドを利用するようにしてください。
View側の表示の仕様が変わってもテストを落とさないようにできます。

2020-05-09 04:00 UTC, yuji91 commented on spec/system/task_spec.rb
> +        expect(page).not_to have_selector 'td', text: task.title
マッチャを変えるでも良いですが、pageの範囲を変えるのも良いです。
対象の画面を確認するとCSSが適用されていることが分かります。

2020-05-12 07:08 UTC, ryota1116 commented on spec/system/task_spec.rb
> +  let(:project) { FactoryBot.create(:project) }
2e3db3f で修正しました。

2020-05-12 07:10 UTC, ryota1116 commented on spec/system/task_spec.rb
> +        expect(page).not_to have_selector 'td', text: task.title
e915d88 で修正しました。
(findで検索してもいいと思いましたが、withinを使いました)

2020-05-12 07:13 UTC, ryota1116 commented on spec/system/task_spec.rb
> +        switch_to_window(windows.last)
`switch_to_window(windows.last)`をコメントアウトして、byebugで確認したところ、htmlの内容が変わっていない(ページ遷移していない)ことが確認できました。

<img width="1336" alt="スクリーンショット 2020-05-12 16 11 24" src="https://user-images.githubusercontent.com/60560627/81649411-3cc24e80-946b-11ea-9269-9e850f9feab4.png">

2020-05-12 07:16 UTC, ryota1116 commented on spec/system/task_spec.rb
> +        expect(find('.task_list')).to have_content task.deadline.strftime('%-m/%d %-H:%M')
aeb7cb8 で修正しました。

ビュー側で`app/helpers/application_helper.rb`の`short_time(datetime)`ヘルパーメソッドを使用していることが確認できたので、TaskモデルのFactorybot、テストコードでも当該ヘルパーを使用し、テストを通しました。

2020-05-12 07:38 UTC, yuji91 commented on spec/system/task_spec.rb
> +        switch_to_window(windows.last)
`switch_to_window`するとpageオブジェクトの内容自体が変更されることも確認できるとイメージがつくと思います！

2020-05-12 08:11 UTC, yuji91 requested changes

2020-05-12 08:11 UTC, yuji91 commented on spec/factories/tasks.rb
> +    deadline { Random.rand(from..to).strftime("%-m/%d %-H:%M") }
別の画面ではdeadlineの表示形式が異なるので、ここで一括でstrftimeしない方が良いかもです！

2020-05-12 08:11 UTC, yuji91 commented on spec/system/task_spec.rb
> +        expect(find('.task_list')).to have_content task.deadline.strftime('%-m/%d %-H:%M')
`strftime("%-m/%d %-H:%M")`を直接定義してしまうと、ヘルパーの仕様が変わるとテストは失敗してしまうかと思います。

2020-05-12 10:10 UTC, ryota1116 commented on spec/system/task_spec.rb
> +        expect(find('.task_list')).to have_content task.deadline.strftime('%-m/%d %-H:%M')
60b67de で再度修正しました。
`spec/rails_helper.rb`にApplicationHelperモジュールをincludeするよう記述することで、spec/配下のファイルでもヘルパーメソッドを使用できるようになりました。

2020-05-12 10:12 UTC, ryota1116 commented on spec/factories/tasks.rb
> +    deadline { Random.rand(from..to).strftime("%-m/%d %-H:%M") }
60b67de で対応しました。

2020-05-12 12:46 UTC, yuji91 approved these changes
LGTM！

2020-05-14 12:16 UTC, merged